name: "Pull Request"
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    paths: [".github/workflows/pull-request.yml"]
jobs:
  pull-request:
    name: "Pull Request"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"