# Ensures underlying ubuntu container image has all of its updates.
name: "Update Image"
on:
  schedule:
    - cron: "0 12 * * *" # Run every day at noon UTC
jobs:
  update-image:
    name: "Build Docker Container Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"